--- #YAML:1.0
name: Mariachi
version: 0.2
license: perl
distribution_type: module
requires:
  Class::Accessor: 0
  Date::Parse: 0
  Email::Find: 0
  Email::Folder: 0.5
  Email::Thread: 0
  Mail::Thread: 2.2
  Memoize: 0
  Module::Build: 0.18
  Template: 0
  URI::Find::Schemeless::Stricter: 0
recommends: {}
build_requires: {}
conflicts: {}
dynamic_config: 1
provides:
  Mariachi:
    file: lib/Mariachi.pm
    version: 0.2
  Mariachi::Folder:
    file: lib/Mariachi.pm
    version: ~
  Mariachi::Message:
    file: lib/Mariachi/Message.pm
    version: ~
  Siesta::Build:
    file: inc/Siesta/Build.pm
    version: ~
  Template::Plugin::Mariachi:
    file: lib/Template/Plugin/Mariachi.pm
    version: ~
generated_by: Module::Build version 0.18
